"/home/xtr/exoterrism/drumlib/clap.scd".loadPath;
"/home/xtr/exoterrism/drumlib/snare.scd".loadPath;
"/home/xtr/exoterrism/drumlib/hat.scd".loadPath;
"/home/xtr/exoterrism/drumlib/meloperc.scd".loadPath;
"/home/xtr/exoterrism/drumlib/cymbals.scd".loadPath;
"/home/xtr/exoterrism/drumlib/kick.scd".loadPath;
"/home/xtr/exoterrism/drumlib/rim.scd".loadPath;
"/home/xtr/exoterrism/drumlib/complex.scd".loadPath;
"/home/xtr/exoterrism/drumlib/buffer.scd".loadPath;



"/home/xtr/exoterrism/bass/bass1.scd".loadPath;


